# -*- coding: utf-8 -*-
"""ClementMCUProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11TG-6aWL9FXlTci6u7MOxDUdZ0G2a98e
"""

!git clone https://github.com/clementliao1031/IST341MarvelProject.git

import pandas as pd
import matplotlib.pyplot as plt
filename = 'MCU - Sheet1.csv'
df = pd.read_csv(filename)        # encoding="utf-8" et al.
print(f"{filename} : file read into a pandas dataframe.")

df.info()

import plotly.express as px
filename = 'MCU - Sheet1.csv'
df = pd.read_csv(filename)
fig = px.scatter(df, x="Title", y="Take",
                 hover_data=['WorldWideBoxOffice'])
fig.show()

import plotly.express as px
df = px.data.iris()
fig = px.scatter(df, x="sepal_width", y="sepal_length", color="species",
                 size='petal_length', hover_data=['petal_width'])
fig.show()

import numpy as np
import pandas as pd
import seaborn as sns
sns.set_theme(style="whitegrid")

rs = np.random.RandomState(365)
values = rs.randn(365, 4).cumsum(axis=0)
dates = pd.date_range("1 1 2024", periods=365, freq="D")
data = pd.DataFrame(values, dates, columns=["Iron Man", "The Incredible Hulk", "Iron Man 2", "Captain America: The First Avenger"])
data = data.rolling(7).mean()

sns.lineplot(data=data, palette="tab10", linewidth=2.5)

!pip install darts

import pandas as pd
from darts import TimeSeries

# Read a pandas DataFrame
df = pd.read_csv("AirPassengers.csv", delimiter=",")

# Create a TimeSeries, specifying the time and value columns
series = TimeSeries.from_dataframe(df, "Month", "#Passengers")

# Set aside the last 36 months as a validation series
train, val = series[:-36], series[-36:]

ts=TimeSeries.from_values(np.arange(33))

#df = pd.read_csv("MCUWorldWideBoxOffice.csv", delimiter=",")
filename = 'MCU - Sheet1.csv'
df = pd.read_csv(filename)        # encoding="utf-8" et al.
# Create a TimeSeries, specifying the time and value columns
series = TimeSeries.from_series(df["Take"])

# Set aside the last 36 months as a validation series
train, val = series[:-4], series[-4:]

from darts.models import ExponentialSmoothing

model = ExponentialSmoothing()
model.fit(train)
prediction = model.predict(len(val), num_samples=1000)

import matplotlib.pyplot as plt

series.plot()
prediction.plot(label="forecast", low_quantile=0.05, high_quantile=0.95)
plt.legend()

